### ISSUE TITLE
weixin支持mac吗？mojo-weixin正常跑起来了，咱装了irssi，输入call chat#weixin#start()没反应。

### ISSUE THREAD

**Issue by PangPangPangPangPang** [wsdjeg/vim-chat#5]
rt 还有／help没反应。

**Comment by wsdjeg** [comment]
你需要装Perl mojiweixin feh neovim

**Comment by FrontMage** [comment]
arch vim8同样没反应，mojo-qq，irssi都装了，然而没反应也不报错。。。

**Comment by wsdjeg** [comment]
肯定是缺少依赖，晚点更新下

**Comment by CXZS-Git** [comment]
请问call命令到底要在哪里输入呢？VIM？还是IRSSI？

**Comment by randomizedthinking** [comment]
我也有同样问题。我是用neovim的，不知道vim-chat对它的支持怎么样？

**Comment by TangMonk** [comment]
我也没反应

**Comment by imze5z** [comment]
https://github.com/vim-chat/vim-chat/blob/master/autoload/chat.vim
